; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Work\bminus\hello-world\hello_world.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	_write
EXTRN	__imp__fputc:PROC
EXTRN	__imp____iob_func:PROC
; Function compile flags: /Ogsp
; File c:\work\bminus\hello-world\hello_world.c
;	COMDAT _write
_TEXT	SEGMENT
_str$ = 8						; size = 4
_write	PROC						; COMDAT

; 8    : write(char str[]) {

	push	ebp
	mov	ebp, esp
	push	esi

; 9    : 	int i;
; 10   : 
; 11   : 	i = 0;
; 12   : 	while (str[i] != 0) {

	mov	esi, DWORD PTR _str$[ebp]
	jmp	SHORT $LN7@write
$LL2@write:

; 13   : 		fputc(str[i], stdout);

	call	DWORD PTR __imp____iob_func
	add	eax, 32					; 00000020H
	push	eax
	movsx	eax, BYTE PTR [esi]
	push	eax
	call	DWORD PTR __imp__fputc
	pop	ecx
	pop	ecx

; 14   : 		i = i + 1;

	inc	esi
$LN7@write:

; 9    : 	int i;
; 10   : 
; 11   : 	i = 0;
; 12   : 	while (str[i] != 0) {

	cmp	BYTE PTR [esi], 0
	jne	SHORT $LL2@write
	pop	esi

; 15   : 	}
; 16   : }

	pop	ebp
	ret	0
_write	ENDP
_TEXT	ENDS
PUBLIC	??_C@_0N@NLPDAPMJ@Hello?5world?6?$AA@		; `string'
PUBLIC	_main
EXTRN	__imp__exit:PROC
;	COMDAT ??_C@_0N@NLPDAPMJ@Hello?5world?6?$AA@
CONST	SEGMENT
??_C@_0N@NLPDAPMJ@Hello?5world?6?$AA@ DB 'Hello world', 0aH, 00H ; `string'
; Function compile flags: /Ogsp
CONST	ENDS
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT

; 3    : 
; 4    :     write("Hello world\n");

	push	OFFSET ??_C@_0N@NLPDAPMJ@Hello?5world?6?$AA@
	call	_write
	pop	ecx

; 5    :     exit(0);

	push	0
	call	DWORD PTR __imp__exit
$LN4@main:
$LN3@main:
	int	3
_main	ENDP
_TEXT	ENDS
END
